services:
  - type: web
    name: rsr-event-platform
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 10000
